version: '3.8'

services:
  api-gateway:
    build:
      context: .
      dockerfile: ./infra/Dockerfile.api-gateway
    ports:
      - '3001:3001'
    environment:
      - PORT=3001
      - AUTH_SERVICE_URL=http://auth-service:3003
      - PROCESS_SERVICE_URL=http://process-service:3002
    env_file:
      - .env
    depends_on:
      - auth-service
      - process-service

  process-service:
    build:
      context: .
      dockerfile: ./infra/Dockerfile.process-service
    ports:
      - '3002:3002'
    environment:
      - PORT=3002
    env_file:
      - .env

  auth-service:
    build:
      context: .
      dockerfile: ./infra/Dockerfile.auth-service
    ports:
      - '3003:3003'
    environment:
      - PORT=3003
    env_file:
      - .env
