FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY ../prisma ./prisma
COPY ../api-gateway ./api-gateway

WORKDIR /app/api-gateway

RUN npx prisma generate --schema=../prisma/schema.prisma

EXPOSE 3000

CMD ["node", "index.js"]