FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY ../prisma ./prisma
COPY ../auth-service ./auth-service

WORKDIR /app/auth-service

RUN npx prisma generate --schema=../prisma/schema.prisma
RUN npm install -g nodemon


EXPOSE 3003

CMD ["nodemon", "index.js"]
